### PR TITLE
full

### PR DESCRIPTION
**Pull request by ilyatsv**
pull request with full code

### CODE REVIEW

**Review by ilyatsv — COMMENTED** [review]
new version

**Comment by gmltA** [comment]
Please, record a video with the game process. I can't figure out what should I do.

**Comment by ilyatsv** [comment]
Uploading t_video5458402755993406086.mp4…

**Comment by ilyatsv** [comment]
https://user-images.githubusercontent.com/62513791/103918894-734a8900-5120-11eb-9d18-bde1a09df4b3.mp4

**Review by gmltA — APPROVED** [review]

**Pull request merged**
